Allow providing custom owner and repo for download artifact action
XanaduAI/cloud-actions pull request #54
Opened 2023-10-24 17:59 UTC by mudit2812

The `download-github-workflow-artifact` action only supports downloading artifacts from the repo where a workflow uses it because users can't specify which repo to download actions from. This PR adds that ability.

2023-10-24 18:02 UTC, mudit2812 commented on download-github-workflow-artifact/README.md
> +the `owner` and `repo` parameters must be set:
```suggestion
the `owner` and `repo` parameters must be set to point to the repository from which
to download the artifact:
```

2023-10-24 18:32 UTC, rashidnhm requested changes

2023-10-24 22:07 UTC, mudit2812 commented
The new action is working. See the `check-diffs` job of [this workflow](https://github.com/PennyLaneAI/qml-diff-checker/actions/runs/6633004591). The steps to download artifacts are `Download Dev Artifact` and `Download Master Artifact` respectively, which run successfully. The downloaded artifacts can be found in the `builds` folder of the repo containing the linked workflow.

2023-10-25 14:06 UTC, rashidnhm requested changes
Minor change, but can we please update the name of the new inputs to be more explicit on what they do. Thanks!

2023-10-25 14:06 UTC, rashidnhm commented on download-github-workflow-artifact/action.yml
> +  owner:
```suggestion
  repository_owner:
```

2023-10-25 14:06 UTC, rashidnhm commented on download-github-workflow-artifact/action.yml
> +  repo:
```suggestion
  repository_name:
```

2023-10-25 14:06 UTC, rashidnhm commented on download-github-workflow-artifact/action.yml
> +          const repoOwner = "${{ inputs.owner }}" || context.repo.owner;
```suggestion
          const repoOwner = "${{ inputs.repository_owner }}" || context.repo.owner;
```

2023-10-25 14:06 UTC, rashidnhm commented on download-github-workflow-artifact/action.yml
> +          const repoName = "${{ inputs.repo }}" || context.repo.repo;
```suggestion
          const repoName = "${{ inputs.repository_name }}" || context.repo.repo;
```

2023-10-25 14:06 UTC, rashidnhm commented on download-github-workflow-artifact/README.md
> +    repo: ${{ steps.repo_information.outputs.name }}
```suggestion
    repository_owner: ${{ steps.repo_information.outputs.owner }}
    repository_name: ${{ steps.repo_information.outputs.name }}
```

2023-10-25 14:06 UTC, rashidnhm commented on download-github-workflow-artifact/download.js
> +module.exports = async ({github}, owner, repo, workflow_run_id, artifact_name_regex, artifact_download_dir, max_retry) => {
```suggestion
module.exports = async ({github}, repository_owner, repository_name, workflow_run_id, artifact_name_regex, artifact_download_dir, max_retry) => {
```

2023-10-25 14:06 UTC, rashidnhm commented on download-github-workflow-artifact/download.js
> +            repo: repo,
```suggestion
            owner: repository_owner,
            repo: repository_name,
```

2023-10-25 14:06 UTC, rashidnhm commented on download-github-workflow-artifact/download.js
> +        repo: repo,
```suggestion
        owner: repository_owner,
        repo: repository_name,
```

2023-10-25 16:55 UTC, rashidnhm approved these changes
One minor update but LGTM otherwise

2023-10-25 16:55 UTC, rashidnhm commented on download-github-workflow-artifact/README.md
> +the `owner` and `repo` parameters must be set to point to the repository from which
```suggestion
the `repository_owner` and `repository_name` parameters must be set to point to the repository from which
```

2023-10-25 17:41 UTC, merged